package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hostinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Hostinfo implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   小区id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.cellid
     *
     * @mbg.generated
     */
    private Integer cellid;

    /**
     * Database Column Remarks:
     *   充电区域位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     * Database Column Remarks:
     *   纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     * Database Column Remarks:
     *   imel 卡号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.imelid
     *
     * @mbg.generated
     */
    private String imelid;

    /**
     * Database Column Remarks:
     *   主题id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.permissionUuid
     *
     * @mbg.generated
     */
    private String permissionuuid;

    /**
     * Database Column Remarks:
     *   最后心跳时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.heartbeattime
     *
     * @mbg.generated
     */
    private Date heartbeattime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   主机软件版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.softwareversion
     *
     * @mbg.generated
     */
    private String softwareversion;

    /**
     * Database Column Remarks:
     *   主机硬件版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.hardwareversion
     *
     * @mbg.generated
     */
    private String hardwareversion;

    /**
     * Database Column Remarks:
     *   主机型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     * Database Column Remarks:
     *   主机状态1默认0禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostinfo.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.id
     *
     * @return the value of hostinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.id
     *
     * @param id the value for hostinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.cellid
     *
     * @return the value of hostinfo.cellid
     *
     * @mbg.generated
     */
    public Integer getCellid() {
        return cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.cellid
     *
     * @param cellid the value for hostinfo.cellid
     *
     * @mbg.generated
     */
    public void setCellid(Integer cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.address
     *
     * @return the value of hostinfo.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.address
     *
     * @param address the value for hostinfo.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.latitude
     *
     * @return the value of hostinfo.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.latitude
     *
     * @param latitude the value for hostinfo.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.longitude
     *
     * @return the value of hostinfo.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.longitude
     *
     * @param longitude the value for hostinfo.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.imelid
     *
     * @return the value of hostinfo.imelid
     *
     * @mbg.generated
     */
    public String getImelid() {
        return imelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.imelid
     *
     * @param imelid the value for hostinfo.imelid
     *
     * @mbg.generated
     */
    public void setImelid(String imelid) {
        this.imelid = imelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.permissionUuid
     *
     * @return the value of hostinfo.permissionUuid
     *
     * @mbg.generated
     */
    public String getPermissionuuid() {
        return permissionuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.permissionUuid
     *
     * @param permissionuuid the value for hostinfo.permissionUuid
     *
     * @mbg.generated
     */
    public void setPermissionuuid(String permissionuuid) {
        this.permissionuuid = permissionuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.heartbeattime
     *
     * @return the value of hostinfo.heartbeattime
     *
     * @mbg.generated
     */
    public Date getHeartbeattime() {
        return heartbeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.heartbeattime
     *
     * @param heartbeattime the value for hostinfo.heartbeattime
     *
     * @mbg.generated
     */
    public void setHeartbeattime(Date heartbeattime) {
        this.heartbeattime = heartbeattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.createtime
     *
     * @return the value of hostinfo.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.createtime
     *
     * @param createtime the value for hostinfo.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.softwareversion
     *
     * @return the value of hostinfo.softwareversion
     *
     * @mbg.generated
     */
    public String getSoftwareversion() {
        return softwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.softwareversion
     *
     * @param softwareversion the value for hostinfo.softwareversion
     *
     * @mbg.generated
     */
    public void setSoftwareversion(String softwareversion) {
        this.softwareversion = softwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.hardwareversion
     *
     * @return the value of hostinfo.hardwareversion
     *
     * @mbg.generated
     */
    public String getHardwareversion() {
        return hardwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.hardwareversion
     *
     * @param hardwareversion the value for hostinfo.hardwareversion
     *
     * @mbg.generated
     */
    public void setHardwareversion(String hardwareversion) {
        this.hardwareversion = hardwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.model
     *
     * @return the value of hostinfo.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.model
     *
     * @param model the value for hostinfo.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostinfo.status
     *
     * @return the value of hostinfo.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostinfo.status
     *
     * @param status the value for hostinfo.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}