package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table monthly
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Monthly implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   小区id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.cellid
     *
     * @mbg.generated
     */
    private Integer cellid;

    /**
     * Database Column Remarks:
     *   月数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.months
     *
     * @mbg.generated
     */
    private Integer months;

    /**
     * Database Column Remarks:
     *   包月金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.frequency
     *
     * @mbg.generated
     */
    private Integer frequency;

    /**
     * Database Column Remarks:
     *   一次限制最大充电时长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.maxchargingtime
     *
     * @mbg.generated
     */
    private Integer maxchargingtime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   状态1默认0禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monthly
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.id
     *
     * @return the value of monthly.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.id
     *
     * @param id the value for monthly.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.cellid
     *
     * @return the value of monthly.cellid
     *
     * @mbg.generated
     */
    public Integer getCellid() {
        return cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.cellid
     *
     * @param cellid the value for monthly.cellid
     *
     * @mbg.generated
     */
    public void setCellid(Integer cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.months
     *
     * @return the value of monthly.months
     *
     * @mbg.generated
     */
    public Integer getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.months
     *
     * @param months the value for monthly.months
     *
     * @mbg.generated
     */
    public void setMonths(Integer months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.amount
     *
     * @return the value of monthly.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.amount
     *
     * @param amount the value for monthly.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.frequency
     *
     * @return the value of monthly.frequency
     *
     * @mbg.generated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.frequency
     *
     * @param frequency the value for monthly.frequency
     *
     * @mbg.generated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.maxchargingtime
     *
     * @return the value of monthly.maxchargingtime
     *
     * @mbg.generated
     */
    public Integer getMaxchargingtime() {
        return maxchargingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.maxchargingtime
     *
     * @param maxchargingtime the value for monthly.maxchargingtime
     *
     * @mbg.generated
     */
    public void setMaxchargingtime(Integer maxchargingtime) {
        this.maxchargingtime = maxchargingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.createtime
     *
     * @return the value of monthly.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.createtime
     *
     * @param createtime the value for monthly.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly.status
     *
     * @return the value of monthly.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly.status
     *
     * @param status the value for monthly.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}