package com.yjdz.zncdz.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public OrderinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderid like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderid not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidIsNull() {
            addCriterion("chargetypeid is null");
            return (Criteria) this;
        }

        public Criteria andChargetypeidIsNotNull() {
            addCriterion("chargetypeid is not null");
            return (Criteria) this;
        }

        public Criteria andChargetypeidEqualTo(Integer value) {
            addCriterion("chargetypeid =", value, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidNotEqualTo(Integer value) {
            addCriterion("chargetypeid <>", value, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidGreaterThan(Integer value) {
            addCriterion("chargetypeid >", value, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("chargetypeid >=", value, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidLessThan(Integer value) {
            addCriterion("chargetypeid <", value, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidLessThanOrEqualTo(Integer value) {
            addCriterion("chargetypeid <=", value, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidIn(List<Integer> values) {
            addCriterion("chargetypeid in", values, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidNotIn(List<Integer> values) {
            addCriterion("chargetypeid not in", values, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidBetween(Integer value1, Integer value2) {
            addCriterion("chargetypeid between", value1, value2, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("chargetypeid not between", value1, value2, "chargetypeid");
            return (Criteria) this;
        }

        public Criteria andChargetypenameIsNull() {
            addCriterion("chargetypename is null");
            return (Criteria) this;
        }

        public Criteria andChargetypenameIsNotNull() {
            addCriterion("chargetypename is not null");
            return (Criteria) this;
        }

        public Criteria andChargetypenameEqualTo(String value) {
            addCriterion("chargetypename =", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameNotEqualTo(String value) {
            addCriterion("chargetypename <>", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameGreaterThan(String value) {
            addCriterion("chargetypename >", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameGreaterThanOrEqualTo(String value) {
            addCriterion("chargetypename >=", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameLessThan(String value) {
            addCriterion("chargetypename <", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameLessThanOrEqualTo(String value) {
            addCriterion("chargetypename <=", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameLike(String value) {
            addCriterion("chargetypename like", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameNotLike(String value) {
            addCriterion("chargetypename not like", value, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameIn(List<String> values) {
            addCriterion("chargetypename in", values, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameNotIn(List<String> values) {
            addCriterion("chargetypename not in", values, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameBetween(String value1, String value2) {
            addCriterion("chargetypename between", value1, value2, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andChargetypenameNotBetween(String value1, String value2) {
            addCriterion("chargetypename not between", value1, value2, "chargetypename");
            return (Criteria) this;
        }

        public Criteria andEquipmentidIsNull() {
            addCriterion("equipmentid is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentidIsNotNull() {
            addCriterion("equipmentid is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentidEqualTo(String value) {
            addCriterion("equipmentid =", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidNotEqualTo(String value) {
            addCriterion("equipmentid <>", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidGreaterThan(String value) {
            addCriterion("equipmentid >", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentid >=", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidLessThan(String value) {
            addCriterion("equipmentid <", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidLessThanOrEqualTo(String value) {
            addCriterion("equipmentid <=", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidLike(String value) {
            addCriterion("equipmentid like", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidNotLike(String value) {
            addCriterion("equipmentid not like", value, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidIn(List<String> values) {
            addCriterion("equipmentid in", values, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidNotIn(List<String> values) {
            addCriterion("equipmentid not in", values, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidBetween(String value1, String value2) {
            addCriterion("equipmentid between", value1, value2, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andEquipmentidNotBetween(String value1, String value2) {
            addCriterion("equipmentid not between", value1, value2, "equipmentid");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(Byte value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(Byte value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(Byte value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(Byte value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(Byte value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(Byte value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<Byte> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<Byte> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(Byte value1, Byte value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(Byte value1, Byte value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("starttime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("starttime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("starttime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("starttime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("starttime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starttime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("starttime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("starttime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("starttime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("starttime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("starttime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("starttime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andConsumptionIsNull() {
            addCriterion("consumption is null");
            return (Criteria) this;
        }

        public Criteria andConsumptionIsNotNull() {
            addCriterion("consumption is not null");
            return (Criteria) this;
        }

        public Criteria andConsumptionEqualTo(BigDecimal value) {
            addCriterion("consumption =", value, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionNotEqualTo(BigDecimal value) {
            addCriterion("consumption <>", value, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionGreaterThan(BigDecimal value) {
            addCriterion("consumption >", value, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("consumption >=", value, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionLessThan(BigDecimal value) {
            addCriterion("consumption <", value, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("consumption <=", value, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionIn(List<BigDecimal> values) {
            addCriterion("consumption in", values, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionNotIn(List<BigDecimal> values) {
            addCriterion("consumption not in", values, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consumption between", value1, value2, "consumption");
            return (Criteria) this;
        }

        public Criteria andConsumptionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consumption not between", value1, value2, "consumption");
            return (Criteria) this;
        }

        public Criteria andChoicesIsNull() {
            addCriterion("choices is null");
            return (Criteria) this;
        }

        public Criteria andChoicesIsNotNull() {
            addCriterion("choices is not null");
            return (Criteria) this;
        }

        public Criteria andChoicesEqualTo(String value) {
            addCriterion("choices =", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesNotEqualTo(String value) {
            addCriterion("choices <>", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesGreaterThan(String value) {
            addCriterion("choices >", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesGreaterThanOrEqualTo(String value) {
            addCriterion("choices >=", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesLessThan(String value) {
            addCriterion("choices <", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesLessThanOrEqualTo(String value) {
            addCriterion("choices <=", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesLike(String value) {
            addCriterion("choices like", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesNotLike(String value) {
            addCriterion("choices not like", value, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesIn(List<String> values) {
            addCriterion("choices in", values, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesNotIn(List<String> values) {
            addCriterion("choices not in", values, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesBetween(String value1, String value2) {
            addCriterion("choices between", value1, value2, "choices");
            return (Criteria) this;
        }

        public Criteria andChoicesNotBetween(String value1, String value2) {
            addCriterion("choices not between", value1, value2, "choices");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeIsNull() {
            addCriterion("selectchargingtime is null");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeIsNotNull() {
            addCriterion("selectchargingtime is not null");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeEqualTo(Integer value) {
            addCriterion("selectchargingtime =", value, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeNotEqualTo(Integer value) {
            addCriterion("selectchargingtime <>", value, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeGreaterThan(Integer value) {
            addCriterion("selectchargingtime >", value, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("selectchargingtime >=", value, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeLessThan(Integer value) {
            addCriterion("selectchargingtime <", value, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeLessThanOrEqualTo(Integer value) {
            addCriterion("selectchargingtime <=", value, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeIn(List<Integer> values) {
            addCriterion("selectchargingtime in", values, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeNotIn(List<Integer> values) {
            addCriterion("selectchargingtime not in", values, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeBetween(Integer value1, Integer value2) {
            addCriterion("selectchargingtime between", value1, value2, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andSelectchargingtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("selectchargingtime not between", value1, value2, "selectchargingtime");
            return (Criteria) this;
        }

        public Criteria andEndingcauseIsNull() {
            addCriterion("endingcause is null");
            return (Criteria) this;
        }

        public Criteria andEndingcauseIsNotNull() {
            addCriterion("endingcause is not null");
            return (Criteria) this;
        }

        public Criteria andEndingcauseEqualTo(Byte value) {
            addCriterion("endingcause =", value, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseNotEqualTo(Byte value) {
            addCriterion("endingcause <>", value, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseGreaterThan(Byte value) {
            addCriterion("endingcause >", value, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseGreaterThanOrEqualTo(Byte value) {
            addCriterion("endingcause >=", value, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseLessThan(Byte value) {
            addCriterion("endingcause <", value, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseLessThanOrEqualTo(Byte value) {
            addCriterion("endingcause <=", value, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseIn(List<Byte> values) {
            addCriterion("endingcause in", values, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseNotIn(List<Byte> values) {
            addCriterion("endingcause not in", values, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseBetween(Byte value1, Byte value2) {
            addCriterion("endingcause between", value1, value2, "endingcause");
            return (Criteria) this;
        }

        public Criteria andEndingcauseNotBetween(Byte value1, Byte value2) {
            addCriterion("endingcause not between", value1, value2, "endingcause");
            return (Criteria) this;
        }

        public Criteria andIsfinishedIsNull() {
            addCriterion("isfinished is null");
            return (Criteria) this;
        }

        public Criteria andIsfinishedIsNotNull() {
            addCriterion("isfinished is not null");
            return (Criteria) this;
        }

        public Criteria andIsfinishedEqualTo(Boolean value) {
            addCriterion("isfinished =", value, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedNotEqualTo(Boolean value) {
            addCriterion("isfinished <>", value, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedGreaterThan(Boolean value) {
            addCriterion("isfinished >", value, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isfinished >=", value, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedLessThan(Boolean value) {
            addCriterion("isfinished <", value, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedLessThanOrEqualTo(Boolean value) {
            addCriterion("isfinished <=", value, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedIn(List<Boolean> values) {
            addCriterion("isfinished in", values, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedNotIn(List<Boolean> values) {
            addCriterion("isfinished not in", values, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedBetween(Boolean value1, Boolean value2) {
            addCriterion("isfinished between", value1, value2, "isfinished");
            return (Criteria) this;
        }

        public Criteria andIsfinishedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isfinished not between", value1, value2, "isfinished");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerIsNull() {
            addCriterion("cumulativepower is null");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerIsNotNull() {
            addCriterion("cumulativepower is not null");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerEqualTo(Integer value) {
            addCriterion("cumulativepower =", value, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerNotEqualTo(Integer value) {
            addCriterion("cumulativepower <>", value, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerGreaterThan(Integer value) {
            addCriterion("cumulativepower >", value, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("cumulativepower >=", value, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerLessThan(Integer value) {
            addCriterion("cumulativepower <", value, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerLessThanOrEqualTo(Integer value) {
            addCriterion("cumulativepower <=", value, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerIn(List<Integer> values) {
            addCriterion("cumulativepower in", values, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerNotIn(List<Integer> values) {
            addCriterion("cumulativepower not in", values, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerBetween(Integer value1, Integer value2) {
            addCriterion("cumulativepower between", value1, value2, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCumulativepowerNotBetween(Integer value1, Integer value2) {
            addCriterion("cumulativepower not between", value1, value2, "cumulativepower");
            return (Criteria) this;
        }

        public Criteria andCardidIsNull() {
            addCriterion("cardid is null");
            return (Criteria) this;
        }

        public Criteria andCardidIsNotNull() {
            addCriterion("cardid is not null");
            return (Criteria) this;
        }

        public Criteria andCardidEqualTo(String value) {
            addCriterion("cardid =", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotEqualTo(String value) {
            addCriterion("cardid <>", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThan(String value) {
            addCriterion("cardid >", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThanOrEqualTo(String value) {
            addCriterion("cardid >=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThan(String value) {
            addCriterion("cardid <", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThanOrEqualTo(String value) {
            addCriterion("cardid <=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLike(String value) {
            addCriterion("cardid like", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotLike(String value) {
            addCriterion("cardid not like", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidIn(List<String> values) {
            addCriterion("cardid in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotIn(List<String> values) {
            addCriterion("cardid not in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidBetween(String value1, String value2) {
            addCriterion("cardid between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotBetween(String value1, String value2) {
            addCriterion("cardid not between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andChargingtimeIsNull() {
            addCriterion("chargingtime is null");
            return (Criteria) this;
        }

        public Criteria andChargingtimeIsNotNull() {
            addCriterion("chargingtime is not null");
            return (Criteria) this;
        }

        public Criteria andChargingtimeEqualTo(Integer value) {
            addCriterion("chargingtime =", value, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeNotEqualTo(Integer value) {
            addCriterion("chargingtime <>", value, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeGreaterThan(Integer value) {
            addCriterion("chargingtime >", value, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("chargingtime >=", value, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeLessThan(Integer value) {
            addCriterion("chargingtime <", value, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeLessThanOrEqualTo(Integer value) {
            addCriterion("chargingtime <=", value, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeIn(List<Integer> values) {
            addCriterion("chargingtime in", values, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeNotIn(List<Integer> values) {
            addCriterion("chargingtime not in", values, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeBetween(Integer value1, Integer value2) {
            addCriterion("chargingtime between", value1, value2, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andChargingtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("chargingtime not between", value1, value2, "chargingtime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeIsNull() {
            addCriterion("lastlandingtime is null");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeIsNotNull() {
            addCriterion("lastlandingtime is not null");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeEqualTo(Date value) {
            addCriterion("lastlandingtime =", value, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeNotEqualTo(Date value) {
            addCriterion("lastlandingtime <>", value, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeGreaterThan(Date value) {
            addCriterion("lastlandingtime >", value, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastlandingtime >=", value, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeLessThan(Date value) {
            addCriterion("lastlandingtime <", value, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeLessThanOrEqualTo(Date value) {
            addCriterion("lastlandingtime <=", value, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeIn(List<Date> values) {
            addCriterion("lastlandingtime in", values, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeNotIn(List<Date> values) {
            addCriterion("lastlandingtime not in", values, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeBetween(Date value1, Date value2) {
            addCriterion("lastlandingtime between", value1, value2, "lastlandingtime");
            return (Criteria) this;
        }

        public Criteria andLastlandingtimeNotBetween(Date value1, Date value2) {
            addCriterion("lastlandingtime not between", value1, value2, "lastlandingtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}