package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orderinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Orderinfo implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderid
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * Database Column Remarks:
     *   计费类型id  收费标准外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.chargetypeid
     *
     * @mbg.generated
     */
    private Integer chargetypeid;

    /**
     * Database Column Remarks:
     *   计费类型名称 计时 包月
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.chargetypename
     *
     * @mbg.generated
     */
    private String chargetypename;

    /**
     * Database Column Remarks:
     *   设备id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.equipmentid
     *
     * @mbg.generated
     */
    private String equipmentid;

    /**
     * Database Column Remarks:
     *   设备端口
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.port
     *
     * @mbg.generated
     */
    private Byte port;

    /**
     * Database Column Remarks:
     *   充电开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.starttime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     * Database Column Remarks:
     *   充电结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     * Database Column Remarks:
     *   消费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.consumption
     *
     * @mbg.generated
     */
    private BigDecimal consumption;

    /**
     * Database Column Remarks:
     *   充电方式  扫码充电  刷卡充电
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.choices
     *
     * @mbg.generated
     */
    private String choices;

    /**
     * Database Column Remarks:
     *   选择充电时长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.selectchargingtime
     *
     * @mbg.generated
     */
    private Integer selectchargingtime;

    /**
     * Database Column Remarks:
     *   断电原因
     *   1充满自停
     *   2达到最大充电时间
     *   3达到预设时间
     *   5用户拔出插座
     *   6负载够大
     *   7用户手动停止充电
     *   9功率过小停止充电
     *   10异常断电
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.endingcause
     *
     * @mbg.generated
     */
    private Byte endingcause;

    /**
     * Database Column Remarks:
     *   是否结束充电
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.isfinished
     *
     * @mbg.generated
     */
    private Boolean isfinished;

    /**
     * Database Column Remarks:
     *   累计电量 w*s
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.cumulativepower
     *
     * @mbg.generated
     */
    private Integer cumulativepower;

    /**
     * Database Column Remarks:
     *   卡号id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.cardid
     *
     * @mbg.generated
     */
    private String cardid;

    /**
     * Database Column Remarks:
     *   充电时长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.chargingtime
     *
     * @mbg.generated
     */
    private Integer chargingtime;

    /**
     * Database Column Remarks:
     *   订单状态 0未开始 1进行中 2已完成 3已取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   订单最后更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.lastlandingtime
     *
     * @mbg.generated
     */
    private Date lastlandingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.id
     *
     * @return the value of orderinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.id
     *
     * @param id the value for orderinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderid
     *
     * @return the value of orderinfo.orderid
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderid
     *
     * @param orderid the value for orderinfo.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.userid
     *
     * @return the value of orderinfo.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.userid
     *
     * @param userid the value for orderinfo.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.chargetypeid
     *
     * @return the value of orderinfo.chargetypeid
     *
     * @mbg.generated
     */
    public Integer getChargetypeid() {
        return chargetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.chargetypeid
     *
     * @param chargetypeid the value for orderinfo.chargetypeid
     *
     * @mbg.generated
     */
    public void setChargetypeid(Integer chargetypeid) {
        this.chargetypeid = chargetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.chargetypename
     *
     * @return the value of orderinfo.chargetypename
     *
     * @mbg.generated
     */
    public String getChargetypename() {
        return chargetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.chargetypename
     *
     * @param chargetypename the value for orderinfo.chargetypename
     *
     * @mbg.generated
     */
    public void setChargetypename(String chargetypename) {
        this.chargetypename = chargetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.equipmentid
     *
     * @return the value of orderinfo.equipmentid
     *
     * @mbg.generated
     */
    public String getEquipmentid() {
        return equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.equipmentid
     *
     * @param equipmentid the value for orderinfo.equipmentid
     *
     * @mbg.generated
     */
    public void setEquipmentid(String equipmentid) {
        this.equipmentid = equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.port
     *
     * @return the value of orderinfo.port
     *
     * @mbg.generated
     */
    public Byte getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.port
     *
     * @param port the value for orderinfo.port
     *
     * @mbg.generated
     */
    public void setPort(Byte port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.starttime
     *
     * @return the value of orderinfo.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.starttime
     *
     * @param starttime the value for orderinfo.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.endtime
     *
     * @return the value of orderinfo.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.endtime
     *
     * @param endtime the value for orderinfo.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.consumption
     *
     * @return the value of orderinfo.consumption
     *
     * @mbg.generated
     */
    public BigDecimal getConsumption() {
        return consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.consumption
     *
     * @param consumption the value for orderinfo.consumption
     *
     * @mbg.generated
     */
    public void setConsumption(BigDecimal consumption) {
        this.consumption = consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.choices
     *
     * @return the value of orderinfo.choices
     *
     * @mbg.generated
     */
    public String getChoices() {
        return choices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.choices
     *
     * @param choices the value for orderinfo.choices
     *
     * @mbg.generated
     */
    public void setChoices(String choices) {
        this.choices = choices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.selectchargingtime
     *
     * @return the value of orderinfo.selectchargingtime
     *
     * @mbg.generated
     */
    public Integer getSelectchargingtime() {
        return selectchargingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.selectchargingtime
     *
     * @param selectchargingtime the value for orderinfo.selectchargingtime
     *
     * @mbg.generated
     */
    public void setSelectchargingtime(Integer selectchargingtime) {
        this.selectchargingtime = selectchargingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.endingcause
     *
     * @return the value of orderinfo.endingcause
     *
     * @mbg.generated
     */
    public Byte getEndingcause() {
        return endingcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.endingcause
     *
     * @param endingcause the value for orderinfo.endingcause
     *
     * @mbg.generated
     */
    public void setEndingcause(Byte endingcause) {
        this.endingcause = endingcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.isfinished
     *
     * @return the value of orderinfo.isfinished
     *
     * @mbg.generated
     */
    public Boolean getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.isfinished
     *
     * @param isfinished the value for orderinfo.isfinished
     *
     * @mbg.generated
     */
    public void setIsfinished(Boolean isfinished) {
        this.isfinished = isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.cumulativepower
     *
     * @return the value of orderinfo.cumulativepower
     *
     * @mbg.generated
     */
    public Integer getCumulativepower() {
        return cumulativepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.cumulativepower
     *
     * @param cumulativepower the value for orderinfo.cumulativepower
     *
     * @mbg.generated
     */
    public void setCumulativepower(Integer cumulativepower) {
        this.cumulativepower = cumulativepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.cardid
     *
     * @return the value of orderinfo.cardid
     *
     * @mbg.generated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.cardid
     *
     * @param cardid the value for orderinfo.cardid
     *
     * @mbg.generated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.chargingtime
     *
     * @return the value of orderinfo.chargingtime
     *
     * @mbg.generated
     */
    public Integer getChargingtime() {
        return chargingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.chargingtime
     *
     * @param chargingtime the value for orderinfo.chargingtime
     *
     * @mbg.generated
     */
    public void setChargingtime(Integer chargingtime) {
        this.chargingtime = chargingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.status
     *
     * @return the value of orderinfo.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.status
     *
     * @param status the value for orderinfo.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.lastlandingtime
     *
     * @return the value of orderinfo.lastlandingtime
     *
     * @mbg.generated
     */
    public Date getLastlandingtime() {
        return lastlandingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.lastlandingtime
     *
     * @param lastlandingtime the value for orderinfo.lastlandingtime
     *
     * @mbg.generated
     */
    public void setLastlandingtime(Date lastlandingtime) {
        this.lastlandingtime = lastlandingtime;
    }
}