package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table powerinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Powerinfo implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.orderid
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     * Database Column Remarks:
     *   指令
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   最大功率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.maxpower
     *
     * @mbg.generated
     */
    private Integer maxpower;

    /**
     * Database Column Remarks:
     *   上传充电时长 秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.seconds
     *
     * @mbg.generated
     */
    private Integer seconds;

    /**
     * Database Column Remarks:
     *   收到时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.receivetime
     *
     * @mbg.generated
     */
    private Date receivetime;

    /**
     * Database Column Remarks:
     *   端口状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column powerinfo.portstatus
     *
     * @mbg.generated
     */
    private String portstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table powerinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.id
     *
     * @return the value of powerinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.id
     *
     * @param id the value for powerinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.orderid
     *
     * @return the value of powerinfo.orderid
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.orderid
     *
     * @param orderid the value for powerinfo.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.code
     *
     * @return the value of powerinfo.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.code
     *
     * @param code the value for powerinfo.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.maxpower
     *
     * @return the value of powerinfo.maxpower
     *
     * @mbg.generated
     */
    public Integer getMaxpower() {
        return maxpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.maxpower
     *
     * @param maxpower the value for powerinfo.maxpower
     *
     * @mbg.generated
     */
    public void setMaxpower(Integer maxpower) {
        this.maxpower = maxpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.seconds
     *
     * @return the value of powerinfo.seconds
     *
     * @mbg.generated
     */
    public Integer getSeconds() {
        return seconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.seconds
     *
     * @param seconds the value for powerinfo.seconds
     *
     * @mbg.generated
     */
    public void setSeconds(Integer seconds) {
        this.seconds = seconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.receivetime
     *
     * @return the value of powerinfo.receivetime
     *
     * @mbg.generated
     */
    public Date getReceivetime() {
        return receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.receivetime
     *
     * @param receivetime the value for powerinfo.receivetime
     *
     * @mbg.generated
     */
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column powerinfo.portstatus
     *
     * @return the value of powerinfo.portstatus
     *
     * @mbg.generated
     */
    public String getPortstatus() {
        return portstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column powerinfo.portstatus
     *
     * @param portstatus the value for powerinfo.portstatus
     *
     * @mbg.generated
     */
    public void setPortstatus(String portstatus) {
        this.portstatus = portstatus;
    }
}