package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rechargeinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Rechargeinfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键id(自增)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   充值订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.orderid
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     * Database Column Remarks:
     *   微信订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.transactionid
     *
     * @mbg.generated
     */
    private Long transactionid;

    /**
     * Database Column Remarks:
     *   用户id(外键)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * Database Column Remarks:
     *   充值时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.rechargetime
     *
     * @mbg.generated
     */
    private Date rechargetime;

    /**
     * Database Column Remarks:
     *   支付类型  微信支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.paytype
     *
     * @mbg.generated
     */
    private String paytype;

    /**
     * Database Column Remarks:
     *   充值金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   充值状态1成功0失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeinfo.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.id
     *
     * @return the value of rechargeinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.id
     *
     * @param id the value for rechargeinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.orderid
     *
     * @return the value of rechargeinfo.orderid
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.orderid
     *
     * @param orderid the value for rechargeinfo.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.transactionid
     *
     * @return the value of rechargeinfo.transactionid
     *
     * @mbg.generated
     */
    public Long getTransactionid() {
        return transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.transactionid
     *
     * @param transactionid the value for rechargeinfo.transactionid
     *
     * @mbg.generated
     */
    public void setTransactionid(Long transactionid) {
        this.transactionid = transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.userid
     *
     * @return the value of rechargeinfo.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.userid
     *
     * @param userid the value for rechargeinfo.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.rechargetime
     *
     * @return the value of rechargeinfo.rechargetime
     *
     * @mbg.generated
     */
    public Date getRechargetime() {
        return rechargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.rechargetime
     *
     * @param rechargetime the value for rechargeinfo.rechargetime
     *
     * @mbg.generated
     */
    public void setRechargetime(Date rechargetime) {
        this.rechargetime = rechargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.paytype
     *
     * @return the value of rechargeinfo.paytype
     *
     * @mbg.generated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.paytype
     *
     * @param paytype the value for rechargeinfo.paytype
     *
     * @mbg.generated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.amount
     *
     * @return the value of rechargeinfo.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.amount
     *
     * @param amount the value for rechargeinfo.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeinfo.status
     *
     * @return the value of rechargeinfo.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeinfo.status
     *
     * @param status the value for rechargeinfo.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}