package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table timinginfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Timinginfo implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   小区id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.cellid
     *
     * @mbg.generated
     */
    private Integer cellid;

    /**
     * Database Column Remarks:
     *   最小功率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.minpower
     *
     * @mbg.generated
     */
    private Integer minpower;

    /**
     * Database Column Remarks:
     *   最大功率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.maxpower
     *
     * @mbg.generated
     */
    private Integer maxpower;

    /**
     * Database Column Remarks:
     *   费率标准/时
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.standard
     *
     * @mbg.generated
     */
    private BigDecimal standard;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   状态1默认0禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timinginfo.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.id
     *
     * @return the value of timinginfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.id
     *
     * @param id the value for timinginfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.cellid
     *
     * @return the value of timinginfo.cellid
     *
     * @mbg.generated
     */
    public Integer getCellid() {
        return cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.cellid
     *
     * @param cellid the value for timinginfo.cellid
     *
     * @mbg.generated
     */
    public void setCellid(Integer cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.minpower
     *
     * @return the value of timinginfo.minpower
     *
     * @mbg.generated
     */
    public Integer getMinpower() {
        return minpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.minpower
     *
     * @param minpower the value for timinginfo.minpower
     *
     * @mbg.generated
     */
    public void setMinpower(Integer minpower) {
        this.minpower = minpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.maxpower
     *
     * @return the value of timinginfo.maxpower
     *
     * @mbg.generated
     */
    public Integer getMaxpower() {
        return maxpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.maxpower
     *
     * @param maxpower the value for timinginfo.maxpower
     *
     * @mbg.generated
     */
    public void setMaxpower(Integer maxpower) {
        this.maxpower = maxpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.standard
     *
     * @return the value of timinginfo.standard
     *
     * @mbg.generated
     */
    public BigDecimal getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.standard
     *
     * @param standard the value for timinginfo.standard
     *
     * @mbg.generated
     */
    public void setStandard(BigDecimal standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.createtime
     *
     * @return the value of timinginfo.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.createtime
     *
     * @param createtime the value for timinginfo.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timinginfo.status
     *
     * @return the value of timinginfo.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timinginfo.status
     *
     * @param status the value for timinginfo.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}