package com.yjdz.zncdz.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Userinfo implements Serializable {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   微信的唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   微信名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   性别 1男 2 女 3保密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.avatarurl
     *
     * @mbg.generated
     */
    private String avatarurl;

    /**
     * Database Column Remarks:
     *   用户真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     * Database Column Remarks:
     *   用户年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   用户电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   用户上次登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.lastlandingtime
     *
     * @mbg.generated
     */
    private Date lastlandingtime;

    /**
     * Database Column Remarks:
     *   用户注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.registrationtime
     *
     * @mbg.generated
     */
    private Date registrationtime;

    /**
     * Database Column Remarks:
     *   用户所属小区id外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.cellid
     *
     * @mbg.generated
     */
    private Integer cellid;

    /**
     * Database Column Remarks:
     *   管理员权限1有0无
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.adminpermission
     *
     * @mbg.generated
     */
    private Boolean adminpermission;

    /**
     * Database Column Remarks:
     *   用户状态 1默认 0 禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.openid
     *
     * @return the value of userinfo.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.openid
     *
     * @param openid the value for userinfo.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.nickname
     *
     * @return the value of userinfo.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.nickname
     *
     * @param nickname the value for userinfo.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.gender
     *
     * @return the value of userinfo.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.gender
     *
     * @param gender the value for userinfo.gender
     *
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.country
     *
     * @return the value of userinfo.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.country
     *
     * @param country the value for userinfo.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.province
     *
     * @return the value of userinfo.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.province
     *
     * @param province the value for userinfo.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.city
     *
     * @return the value of userinfo.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.city
     *
     * @param city the value for userinfo.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.avatarurl
     *
     * @return the value of userinfo.avatarurl
     *
     * @mbg.generated
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.avatarurl
     *
     * @param avatarurl the value for userinfo.avatarurl
     *
     * @mbg.generated
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.realname
     *
     * @return the value of userinfo.realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.realname
     *
     * @param realname the value for userinfo.realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.age
     *
     * @return the value of userinfo.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.age
     *
     * @param age the value for userinfo.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.lastlandingtime
     *
     * @return the value of userinfo.lastlandingtime
     *
     * @mbg.generated
     */
    public Date getLastlandingtime() {
        return lastlandingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.lastlandingtime
     *
     * @param lastlandingtime the value for userinfo.lastlandingtime
     *
     * @mbg.generated
     */
    public void setLastlandingtime(Date lastlandingtime) {
        this.lastlandingtime = lastlandingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.registrationtime
     *
     * @return the value of userinfo.registrationtime
     *
     * @mbg.generated
     */
    public Date getRegistrationtime() {
        return registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.registrationtime
     *
     * @param registrationtime the value for userinfo.registrationtime
     *
     * @mbg.generated
     */
    public void setRegistrationtime(Date registrationtime) {
        this.registrationtime = registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.cellid
     *
     * @return the value of userinfo.cellid
     *
     * @mbg.generated
     */
    public Integer getCellid() {
        return cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.cellid
     *
     * @param cellid the value for userinfo.cellid
     *
     * @mbg.generated
     */
    public void setCellid(Integer cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.adminpermission
     *
     * @return the value of userinfo.adminpermission
     *
     * @mbg.generated
     */
    public Boolean getAdminpermission() {
        return adminpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.adminpermission
     *
     * @param adminpermission the value for userinfo.adminpermission
     *
     * @mbg.generated
     */
    public void setAdminpermission(Boolean adminpermission) {
        this.adminpermission = adminpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.status
     *
     * @return the value of userinfo.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.status
     *
     * @param status the value for userinfo.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}