package com.yjdz.zncdz.dao;

import com.yjdz.zncdz.entity.Cardinfo;
import com.yjdz.zncdz.entity.CardinfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface CardinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    long countByExample(CardinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int deleteByExample(CardinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int insert(Cardinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int insertSelective(Cardinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    List<Cardinfo> selectByExample(CardinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    Cardinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cardinfo record, @Param("example") CardinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cardinfo record, @Param("example") CardinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cardinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cardinfo record);
}