package com.yjdz.zncdz.dao;

import com.yjdz.zncdz.entity.Hostinfo;
import com.yjdz.zncdz.entity.HostinfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface HostinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    long countByExample(HostinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int deleteByExample(HostinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int insert(Hostinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int insertSelective(Hostinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    List<Hostinfo> selectByExample(HostinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    Hostinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Hostinfo record, @Param("example") HostinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Hostinfo record, @Param("example") HostinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Hostinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hostinfo record);
}