package com.yjdz.zncdz.dao;

import com.yjdz.zncdz.entity.Monthly;
import com.yjdz.zncdz.entity.MonthlyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository

public interface MonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    long countByExample(MonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int deleteByExample(MonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int insert(Monthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int insertSelective(Monthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    List<Monthly> selectByExample(MonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    Monthly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Monthly record, @Param("example") MonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Monthly record, @Param("example") MonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Monthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Monthly record);
}