package com.yjdz.zncdz.dao;

import com.yjdz.zncdz.entity.Rechargeinfo;
import com.yjdz.zncdz.entity.RechargeinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    long countByExample(RechargeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int deleteByExample(RechargeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int insert(Rechargeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int insertSelective(Rechargeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    List<Rechargeinfo> selectByExample(RechargeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    Rechargeinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Rechargeinfo record, @Param("example") RechargeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Rechargeinfo record, @Param("example") RechargeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Rechargeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rechargeinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Rechargeinfo record);
}