package com.yjdz.zncdz.dao;

import com.yjdz.zncdz.entity.Timinginfo;
import com.yjdz.zncdz.entity.TiminginfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TiminginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    long countByExample(TiminginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int deleteByExample(TiminginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int insert(Timinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int insertSelective(Timinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    List<Timinginfo> selectByExample(TiminginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    Timinginfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Timinginfo record, @Param("example") TiminginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Timinginfo record, @Param("example") TiminginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Timinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timinginfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Timinginfo record);
}